.readthedocs.yml, docs/requirements.txt, docs/source/conf.py
Read the docs configs
@efredriksson-modelon  - Poetry is not supported by sphinx hence the need for requirements.txt.
=> fix: Adding read the docs specifics

modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py
This PR fixes a bug where an additional set of quotes were added to the result file_name returned by the **get_result()** function.
**How to test**
```
import uuid
client = Client(url="http://localhost:8080/")
workspace = client.create_workspace(uuid.uuid4().hex)
linearize = workspace.get_custom_function('dynamic')
fmu = model.compile(compiler_options=linearize.get_compiler_options()).wait()
experiment_definition = fmu.new_experiment_definition(linearize)
result, file_name = case.get_result()
with open(file_name, "wb") as f:
f.write(result)
```
@jacobtaxen
=> fix: Striping quotes from suggested filename

modelon/impact/client/__init__.py, modelon/impact/client/experiment_definition.py, modelon/impact/client/sal/service.py, tests/impact/client/test_entities.py, tests/impact/client/test_experiment_definition.py
**Left To Do**
1. Update readTheDocs. Will be done in a separate PR if changes are approved.
**How to test**
Try to simulate the test below:-
```
from modelon.impact.client.experiment_definition import SimpleExperimentExtension
import uuid
client = Client(url="http://localhost:8080/")
workspace = client.create_workspace(uuid.uuid4().hex)
fmu = model.compile(
compiler_options=dynamic.get_compiler_options().with_values(
generate_html_diagnostics=False
)
).wait()
experiment_definition = fmu.new_experiment_definition(
dynamic.with_parameters(start_time=0.0, final_time=2.0), …
```
=> feat: Possibility to add extensions to experiment

docs/requirements.txt
ReadTheDocs failed to generate docs for https://modelon-impact-client.readthedocs.io/en/beta/modelon.impact.client.html#modelon-impact-client-client-module due to an import failure for semanticversion package. Unfortunately we can't use the toml file to generate specify dependencies while generating docs.
=> fix: Resolves missing docs for client module

modelon/impact/client/entities.py, modelon/impact/client/experiment_definition.py, modelon/impact/client/operations.py, modelon/impact/client/options.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py, tests/impact/client/test_entities.py, tests/impact/client/test_experiment_definition.py, tests/impact/client/test_operations.py
**How to test-**
**Basic Tests**
1. Execute the below code once to create an FMU. 
2. Execute the code again. This time model should not be recompiled(see logs)
3. Change the option generate_html_diagnostics to true. Execute the code again, the Model should recompile now.
**Coupling with UI test.**
1.  Compile a model in UI.
2. Change any param in modeling mode
3. Simulate the model using client. Check if parameter modifiers have been correctly applied
```
client = Client(url="http://localhost:8080")
workspace = client.create_workspace("Hello6")
model = workspace.get_model("Workspace.PID_Controller")
fmu = model.compile(
compiler_options=dynamic.get_compiler_options(), compiler_log_level="w", …
```
=> feat: Added checks to use cached FMU if available

modelon/impact/client/__init__.py, modelon/impact/client/entities.py, modelon/impact/client/experiment_definition.py, tests/impact/client/fixtures.py, tests/impact/client/test_experiment_definition.py
You should be able to do :-
```
from modelon.impact.client import Client, Range, SimpleExperimentExtension
client = Client(url="http://localhost:8080")
workspace = client.create_workspace("Test")
experiment_definition = model.new_experiment_definition(dynamic).with_cases(
[{'PI.k': 20}, {'PI.k': 30}]
)
experiment_definition = model.new_experiment_definition(dynamic).with_extensions(
[
SimpleExperimentExtension(
parameter_modifiers={'start_time': 0.0, 'final_time': 2.0}
).with_modifiers({'PI.k': 20})
]
)
experiment_definition = model.new_experiment_definition(dynamic).with_modifiers(
{'PI.yMax': Range(12, 15, 4)}
)
print(experiment_definition.to_dict())
exp = …
```
=> feat: Added support for modelica_class name based workflows

modelon/impact/client/entities.py, modelon/impact/client/experiment_definition.py, modelon/impact/client/operations.py, tests/impact/client/fixtures.py, tests/impact/client/test_entities.py
This PR adds support to fetch FMU's executed in each case
```
from modelon.impact.client import Client, Choices, Range
client = Client()
workspace = client.create_workspace("Hye12")
dynamic = workspace.get_custom_function("dynamic")
model = workspace.get_model("Modelica.Fluid.Examples.HeatingSystem")
experiment_definition = model.new_experiment_definition(dynamic).with_modifiers(
{'pipe.nNodes': Choices(2, 3)}
)
print(experiment_definition.to_dict())
print(exp.is_successful())
fmu = case.get_fmu()
print(fmu.id)
case = exp.get_case('case_2')
fmu = case.get_fmu()
print(fmu.id)
```
=> feat: Added support for fetching fmus executed for a case

modelon/impact/client/entities.py, modelon/impact/client/operations.py, tests/impact/client/fixtures.py, tests/impact/client/test_entities.py
This PR was for fixing 2 issues. The first was that the `__repr__` method for Model was broken. The second was that the new Experiment Status that the API can return was not taken care of. While doing this, I felt the need to refactor how the 'info' and 'is_successful' methods work to make sure that the user gets a good experience.
For the first it is enough to run something like:
`workspace.get_model('asdfasdf')`
in a Python shell.
For the second I recommend sending a too large experiment and see that is_successful returns False and that run_info.errors show something reasonable.
=> Handle experiments that fail and some minor fixes

docs/source/tutorial.rst, modelon/impact/client/client.py
The docs claimed that you can specify a name when uploading a workspace, which you can't anymore. The current upload_workspace takes a path to a zip-file as its only argument
=> fix: change docs to match current signature of client.upload_workspace

docs/source/tutorial.rst, modelon/impact/client/entities.py, modelon/impact/client/experiment_definition.py
Following the previous documentation would give you a very hard to decipher error message. 
I have also added a ,*, in the model.new_experiment_definition signature to enforce the keywords, so that you have to set the arguments as keyword args. 
(Also a lot of trailing whitespaces have been removed)
=> fix: correct docs on model.new_experiment_definition

modelon/impact/client/entities.py, tests/impact/client/test_entities.py
The code example in the documentation:
```
fmus = set(case.get_fmu() for case in exp.get_cases())
```
did not work because the fmu entity was not hashable.
=> fix: exmple creating set of all FMUs does now works

modelon/impact/client/entities.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py
WAMS: https://modelonproducts.atlassian.net/browse/WAMS-8272
**Key changes**
1. Add delete methods to the Experiment and ModelExecutable enteties. 
2. Add unit tests validating that the correct http call will be done when delete method is called.
**How to test**
```
import time
workspace = client.create_workspace("Test123")
fmu = model.compile(compiler_options=dynamic.get_compiler_options()).wait()
time.sleep(1)
#fmu.delete()
experiment_definition = fmu.new_experiment_definition(dynamic)
time.sleep(1)
exp.delete()
```
=> feat: Added API support for deleting fmus and experiments

modelon/impact/client/entities.py, tests/impact/client/fixtures.py, tests/impact/client/test_entities.py
Should be possible to execute the following workflow now :-
```
from modelon.impact.client import Client, Range
workspace = client.create_workspace("Case174")
experiment_definition = model.new_experiment_definition(
dynamic.with_parameters(start_time=0.0, final_time=2.0),
simulation_options=dynamic.get_simulation_options().with_values(ncp=500),
solver_options={'atol': 1e-8},
).with_modifiers({'inertia1.J': 2, 'PI.k': Range(10, 100, 5)})
experiment = workspace.create_experiment(experiment_definition)
result = experiment.execute().wait()
```
=> feat: Support for executing a created experiment

modelon/impact/client/entities.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py, tests/impact/client/test_entities.py
The following workflow should now work ->
```
from modelon.impact.client import Client, Range
workspace = client.create_workspace("filter")
experiment_definition = model.new_experiment_definition(
dynamic.with_parameters(start_time=0.0, final_time=2.0),
simulation_options=dynamic.get_simulation_options().with_values(ncp=500),
solver_options={'atol': 1e-8},
).with_modifiers({'inertia1.J': 2, 'PI.k': Range(102, 103, 5)})
experiment = workspace.create_experiment(experiment_definition)
case_generation = experiment.execute(with_cases=[]).wait()
case_3 = case_generation.get_cases()[2]
result = …
```
=> Case filter

modelon/impact/client/entities.py, modelon/impact/client/operations.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py, tests/impact/client/test_entities.py, tests/impact/client/test_operations.py
Should be possible to execute the following workflow - 
```
import uuid
from modelon.impact.client import (
Client,
SimpleModelicaExperimentDefinition,
)
workspace_id = uuid.uuid4().hex
client = Client(url="http://127.0.0.1:8080/")
workspace = client.create_workspace(workspace_id)
dyn_model = workspace.get_model('Modelica.Blocks.Examples.PID_Controller')
exp_definition = SimpleModelicaExperimentDefinition(dyn_model, dynamic)
experiment = workspace.create_experiment(exp_definition)
experiment = experiment.execute().wait(timeout=120)
case = experiment.get_case('case_1')
res = case.get_trajectories()
assert len(res['PI.y']) == 502
assert res['PI.y'][-1] == -7.00030035862339
case.input.analysis.parameters = {"start_time": 0, "final_time": 90} …
```
=> feat: Added support to update and execute cases

modelon/impact/client/entities.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py, tests/impact/client/test_entities.py
Should now be possible to set experiment labels
```
import uuid
from modelon.impact.client import (
Client,
SimpleModelicaExperimentDefinition,
)
workspace_id = uuid.uuid4().hex
client = Client(url="http://127.0.0.1:8080/")
workspace = client.create_workspace(workspace_id)
dyn_model = workspace.get_model('Modelica.Blocks.Examples.PID_Controller')
exp_definition = SimpleModelicaExperimentDefinition(dyn_model, dynamic)
experiment = workspace.create_experiment(exp_definition)
experiment = experiment.execute().wait()
experiment.set_label('Doomed')
```
=> feat: Added support to set labels for experiment

modelon/impact/client/entities.py
This PR removes checking the "not_started" key in run_info while asserting successful experiment. This would otherwise give a false assertion for experiments run with case filter.
=> fix: not_started status not checked for successful experiment

modelon/impact/client/entities.py, modelon/impact/client/experiment_definition.py, tests/impact/client/test_entities.py, tests/impact/client/test_experiment_definition.py
This PR added support for initializing from Experiment and Case based on https://modelonproducts.atlassian.net/browse/WAMS-7563. 
The input property in class is updated to just use the _info variable as in any workflow of retrieving case objects this info will always be available. Also the _get_info() method is now updated to do the GET call to fetch latest metadata about the case. This is needed since now cases can be updated and re-executed and this information can change.
=> feat: Added support for initializing from case and experiment

modelon/impact/client/entities.py, modelon/impact/client/operations.py
This changes so case data is not fetched excessively. It also makes things more deterministic by only fetching case data when a case object is created.
=> More review fixes

modelon/impact/client/entities.py, modelon/impact/client/operations.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py, tests/impact/client/test_entities.py, tests/impact/client/test_operations.py
Code to test - 
```
client = Client(url="http://127.0.0.1:8080/")
workspace = client.create_workspace('Test')
res_path = r"C:\Users\AbhilashKumar\Downloads\Result 1.mat"
a = workspace.upload_result(res_path ).wait()
a.delete()
```
@andrewwren-modelon I have a few questions on the API end - 
1. Is it possible to upload any file through this API, not just mat? What I observed that any file below 100 MB can be uploaded and the files are renamed to result.mat. 
2. Does the API POST/uploads/results hold the execution until the file is uploaded ? I wasn't able to slow it down so that the wait function can come into effect even with a larger file so was unsure of the behavior.
=> Import external result

modelon/impact/client/entities.py, modelon/impact/client/experiment_definition.py, tests/impact/client/test_entities.py, tests/impact/client/test_experiment_definition.py
Code to test
```
from modelon.impact.client.experiment_definition import (
SimpleModelicaExperimentDefinition,
)
from modelon.impact.client.client import Client
import uuid
base_url = "http://127.0.0.1:8080/"
workspace_id = uuid.uuid4().hex
client = Client(url=base_url)
workspace = client.create_workspace(workspace_id)
steady_state = workspace.get_custom_function('steady state')
workspace.upload_model_library(
r"C:\UserData\Modelon\WEP\IMPACT\diraction\src\mimp-base\tests\files\test_mo_files\steady_state.mo"
)
ss_fail_model = workspace.get_model('ExampleModels.SSFail')
exp_def_1 = exp_definition = SimpleModelicaExperimentDefinition(
ss_fail_model, steady_state
)
result = workspace.upload_result(
r"C:\Users\AbhilashKumar\Downloads\result_to_init.mat"
).wait()
experiment_1 = …
```
=> Initialize from external result

Makefile, modelon/impact/client/client.py, modelon/impact/client/entities.py, modelon/impact/client/operations.py, modelon/impact/client/options.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/test_entities.py
⚠️⚠️ Second commit contains only lint changes, reviewing the commits separately will be easier ⚠️⚠️
This PR fixes the issue where multiple case updates are done and the wrong value for 'consistent' where sent to the server, resulting in a server error. With this PR this code is possible to run with no errors:
```
c = Client()
w = client.create_workspace('test_multiple_updates')
m = w.get_model('Modelica.Blocks.Examples.PID_Controller')
dynamic = w.get_custom_function('dynamic')
exp_def = m.new_experiment_definition(dynamic)
exp = w.create_experiment(exp_def).execute().wait()
case.input.parametrization = {'inertia1.J': 5}
case.update()
case.input.parametrization = {'inertia1.J': 6}
case.update()
```
=> Update case multiple times fix

modelon/impact/client/entities.py, tests/impact/client/fixtures.py, tests/impact/client/test_entities.py
This PR adds the attribute 'consistent' to the case entity. This will help a user know if they should use the result of a case or not.
Example code on a workspace with at least one experiment with at least one case:
```
all_experiments = workspace.get_experiments()
case = all_experiments[0].get_cases()[0]
case.run_info.consistent
True
case.input.parametrization = {'a': 5}
case.update()
case.run_info.consistent
False
```
=> feat: possible to check if a case is consistent

modelon/impact/client/entities.py, modelon/impact/client/experiment_definition.py, tests/impact/client/fixtures.py, tests/impact/client/test_entities.py, tests/impact/client/test_experiment_definition.py
**Code to test**
The following code snippets should raise an exception for trying to re-init. Also please test if reint with the same entity works.
```
import uuid
workspace_id = uuid.uuid4().hex
c = Client(url="http://127.0.0.1:8080")
w = c.create_workspace(workspace_id)
m = w.get_model('Modelica.Blocks.Examples.PID_Controller')
res = w.upload_result(r"C:\Users\AbhilashKumar\Downloads\result_to_init.mat").wait()
dynamic = w.get_custom_function('dynamic')
exp_def = m.new_experiment_definition(dynamic)
exp_1 = w.create_experiment(exp_def).execute().wait()
exp_2 = w.create_experiment(exp_def).execute().wait()
case_exp_2 = exp_2.get_case('case_1')
case_exp_1 = exp_1.get_case('case_1')
case_exp_1.initialize_from_case = case_exp_2 …
```
=> fix: Assert reinitialization with multiple entities

modelon/impact/client/client.py, tests/impact/client/test_client.py
This fixes the issue where you don't have any API key configured (remove api.key file) and would run
```
c = Client(url='https://impact.modelon.com/', interactive=True)
```
and then in the prompt for API key just press enter. Then it would not count this as an Anonymous login in Client (but would do so server side), so you don't get any warning. We would also save this empty string to disk for next time as if it was a valid API key.
=> fix: given empty string as API key, do anon login and don't save key

.releaserc, Dockerfile, Jenkinsfile, Makefile, modelon/impact/client/client.py, modelon/impact/client/credential_manager.py, modelon/impact/client/jupyterhub/__init__.py, modelon/impact/client/jupyterhub/authorize.py, modelon/impact/client/jupyterhub/exceptions.py, modelon/impact/client/jupyterhub/sal.py, modelon/impact/client/sal/exceptions.py, modelon/impact/client/sal/service.py, setup.cfg, tests/impact/client/fixtures.py, tests/impact/client/jupyterhub/fixtures.py, tests/impact/client/jupyterhub/test_authorize.py, tests/impact/client/jupyterhub/test_sal.py, tests/impact/client/test_client.py
This PR adds support to the client to access an Impact server running in a Jupyterhub. It will be automatically detected if the server the user is pointing against is a Jupyterhub and if that case we will authorize against. This authorization is like how we handle API keys in Impact. Once authorized a new URL and context exists to start the regular Impact client business.
=> Jupyterhub authorization

README.md, modelon/impact/client/entities.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py, tests/impact/client/test_entities.py, tests/impact/client/test_operations.py
This PR adds support for attaching a custom user_data dictionary object to experiments.
It can be added like this:
```
experiment = workspace.create_experiment(experiment_definition, user_data={"customProp": customValue})
```
or like this:
```
experiment = workspace.execute(experiment_definition, user_data={"customProp": customValue}).wait()
```
and then later retrieved:
```
user_data = experiment.metadata.user_data
```
The test additions are probably the main pain-point in this PR, suggestions for improvements are most welcome :pray:
=> Experiment user data

modelon/impact/client/client.py, modelon/impact/client/sal/exceptions.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py, tests/impact/client/test_operations.py
This PR solves so you will login again if your JWT expires. This is particularly important for long running simulations that run over the night. The implementation is done by a decorator that is applied to all methods of the service classes. This decorator will look for a HTTP 401 failure, re-login, and retry.
```
c = Client(url='...', interactive=True)
print(c.get_workspaces())
c._sal._http_client._context.session.cookies.clear() # Ugly hack to ensure next request will fail with a 401
print(c.get_workspaces())
```
Previously this code would fail but now it should recover.
=> feat: login again if there is an authentication error

modelon/impact/client/client.py, modelon/impact/client/exceptions.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py, tests/impact/client/test_client.py, tests/impact/client/test_entities.py, tests/impact/client/test_operations.py
This PR uses the new version of the API where you can get the license of current user. If no license an exception is raised informing the user. I am very open to improvements to the error message; this was the best I could think of.
=> Check license after login

modelon/impact/client/client.py, modelon/impact/client/entities.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py, tests/impact/client/test_client.py, tests/impact/client/test_entities.py
This PR aims to remove workspace lock/unlock functionality and the corresponding tests.
As a consequence this could mean that the new client API release would require Impact API version 2.0.0 or higher where locks are removed.
However since in practice the python client is only changed to use a subset of the Impact API (i.e. the current Impact API minus locks) it is compatible with older impact versions. So a suggestion is to not update the supported version range to exclude older versions.
=> feat: remove workspace locks

modelon/impact/client/client.py, modelon/impact/client/entities.py, modelon/impact/client/sal/service.py, tests/impact/client/fixtures.py, tests/impact/client/sal/test_services.py, tests/impact/client/test_client.py, tests/impact/client/test_entities.py
Jira - https://modelonproducts.atlassian.net/browse/WAMS-8882
Code to test
```
workspace = client.create_workspace("Pop1")
model = workspace.get_model("Modelica.Mechanics.Translational.Examples.SignConvention")
experiment_definition = model.new_experiment_definition(dynamic)
result, file_name = case.get_result(format="csv")
with open(file_name, "w") as f:
f.write(result)
result, file_name = case.get_result(format="mat")
with open(file_name, "wb") as f:
f.write(result)
```
=> feat: Added possibility to specify result format

.devcontainer/devcontainer.json, Dockerfile, Makefile, README.md
An early present to help with writing code 😄. This configuration builds on the existing Dockerfile and should not require too much work to keep up to date. It gives an out of box working dev environment in VS Code that is very nice and productive.
* Open project and click "Reopen in Container"
* Observe that you have autoformat on save and flake8 warnings
* It is also possible to run a single test directly from the code! (though it seems you have to wait a 10-20s after opening the first test file until you see the icons):
=> chore: add dev container as a developer alternative

modelon/impact/client/entities.py
A small PR to address this ticket -> https://otrs.modelon.com/index.pl?Action=AgentTicketZoom;TicketID=39712
=> fix: add started to CaseStatus enum to mirror impact Case statuses

modelon/impact/client/asserts.py, modelon/impact/client/entities/custom_function.py, modelon/impact/client/entities/model.py, modelon/impact/client/entities/model_executable.py, modelon/impact/client/experiment_definition/extension.py, modelon/impact/client/experiment_definition/util.py, modelon/impact/client/options.py, tests/impact/client/entities/test_custom_function.py, tests/impact/client/fixtures.py, tests/impact/client/test_options.py
Code to test
```
client = Client(url="https://jhmi.modelon.com", interactive=True)
workspace = client.create_workspace("pop")
experiment_definition = model.new_experiment_definition(
dynamic.with_parameters(start_time=0.0, final_time=2.0),
simulation_options=dynamic.get_simulation_options().with_result_filter(
['*.phi', '*.y']
),
solver_options={'atol': 1e-8},
)
```
**Jira** - https://modelonproducts.atlassian.net/browse/WAMS-10828
=> feat: added possibility to set defaults for custom functions and specify variable filter as a list of strings

modelon/impact/client/sal/uri.py, tests/impact/client/sal/test_uri.py
Some of the relative URLs added in new methods where starting with a slash. This would lead to incorrect concatenated results for some cases. This PR changes the URI class so it does not care about this.
=> fix: concatination of URLs handles starting slash on relative part

Dockerfile, docs/source/setup.rst, modelon/impact/client/client.py, modelon/impact/client/jupyterhub/authorize.py
This PR adds hints for the interactive help text during login with URL to where key/token can be generated. This should in particularly help with users not know for sure where the boundary between JH and Impact goes.
Run the following code (be sure you do not already have setup token/key for impact.modelon.cloud)
```
client = Client('https://impact.modelon.cloud/', interactive=True)
```
And follow the prompts to where token/key can be generated:
=> Token api key url hint

Dockerfile, modelon/impact/client/entities/model_executable.py, tests/impact/client/entities/test_model_exe.py
```
client = Client(url="https://jhmi.modelon.com/", interactive=True,)
workspace = client.get_workspace("test")
model = workspace.get_model("Test.PID_Controller")
compiler_options = dynamic.get_compiler_options().with_values(c_compiler='gcc')
runtime_options = {'cs_solver': 0}
fmu = model.compile(compiler_options, runtime_options).wait()
print(fmu.is_successful())
fmu_path = fmu.download('/home/jovyan/impact/workspaces/test')
log = fmu.get_log()
log.show()
```
=> fix: assert compilation is successful before calling download FMU api

.readthedocs.yml, docs/requirements.txt, docs/source/conf.py, poetry.lock, pyproject.toml
This PR fixes the build issues with RTD caused by having a different requirements file for docs. I have now standardized it to use the PyProject.toml.
Also while debugging this, I found a cool extension which allows you to search as you type (see https://readthedocs-sphinx-search.readthedocs.io/en/latest/) which I have now added to the client.
I have temporarily enabled viewing of  https://modelon-impact-client.readthedocs.io/en/docs-build-fix/ to help with this PR review. Thanks!
=> Docs build fix

modelon/impact/client/client.py, modelon/impact/client/configuration.py, tests/impact/client/test_configuration.py
This PR changes the default url to https://impact.modelon.cloud/ if no url is provided by user or no environmental variable is set
=> fix: default to https://impact.modelon.cloud/ if no url is provided by user or no environmental variable is set

modelon/impact/client/entities/project.py, modelon/impact/client/operations/content_import.py, tests/impact/client/entities/test_project.py
Renamed newly added methods to use "import_" instead of "upload_". NOTE:- I have not updated the old ones using 'upload' terminology to not do any breaking change.
=> Upload import

docs/source/install.rst
https://modelonproducts.atlassian.net/browse/FLOW-24
=> fix: added mapping for python client-MI version compatibility

modelon/impact/client/entities/case.py, modelon/impact/client/entities/experiment.py, modelon/impact/client/entities/model.py, modelon/impact/client/entities/workspace.py, modelon/impact/client/operations/base.py, modelon/impact/client/operations/case.py, modelon/impact/client/operations/content_import.py, modelon/impact/client/operations/experiment.py, modelon/impact/client/operations/external_result_import.py, modelon/impact/client/operations/fmu_import.py, modelon/impact/client/operations/model_executable.py, modelon/impact/client/operations/project_import.py, modelon/impact/client/operations/workspace/conversion.py, modelon/impact/client/operations/workspace/exports.py, modelon/impact/client/operations/workspace/imports.py, tests/impact/client/entities/test_project.py, tests/impact/client/operations/imports/test_external_result.py, tests/impact/client/operations/test_case.py, tests/impact/client/operations/test_experiment.py, tests/impact/client/operations/test_model_exe.py
BREAKING CHANGE: the status method in all operations class inheriting BaseOperation class is now a property
=> fix: the Status method in Operations class is now a property

modelon/impact/client/entities/experiment.py, modelon/impact/client/entities/result.py, modelon/impact/client/sal/experiment.py, modelon/impact/client/sal/http.py, modelon/impact/client/sal/request.py, tests/impact/client/entities/test_experiment.py, tests/impact/client/fixtures/fixtures.py, tests/impact/client/helpers.py, tests/impact/client/sal/test_experiment_service.py
Jira - https://modelonproducts.atlassian.net/browse/FLOW-36
How to test 
```
from modelon.impact.client import Client, Range
import pandas as pd
client = Client(
url="https://jhmi-staging.modelon.com/user/abhilash.kumar@modelon.com/impact",
interactive=True,
)
ws = client.get_workspace("tpl")
model = ws.get_model('Unnamed.Structural')
cf = ws.get_custom_function('dynamic')
exp_def = model.new_experiment_definition(cf).with_modifiers({'b': Range(1, 5, 5)})
exp = ws.execute(exp_def).wait()
traj = exp.get_last_time_point(["a", "b", "c"])
print(traj.as_lists())
print(traj.cases)
print(traj.variables)
df = pd.DataFrame(data=traj.as_lists(), columns=traj.variables, index=traj.cases)
df.index.name = "Cases"
print(df)
```
=> feat: added support to fetch only last point for a result trajectory

Dockerfile
We seems to have run into https://github.com/semantic-release/release-notes-generator/issues/459 trying to do the 3.0.0 release that contains 200+ commits
=> chore: lock semantic release bot to older version due to issue

modelon/impact/client/client.py, modelon/impact/client/entities/workspace.py, modelon/impact/client/sal/workspace.py, tests/impact/client/entities/test_workspace.py
Jira - https://modelonproducts.atlassian.net/browse/FLOW-248
```
client = Client(url="https://jhmi-staging.modelon.com/", interactive=True)
workspaces =  client.get_workspace_by_name('SyncPubTest')
if not workspaces:
local_workspace = client.create_workspace('SyncPubTest')
else:
local_workspace = workspaces[0]
published_workspaces = client.get_published_workspaces(owner_username='abhilash.kumar@modelon.com', name='SyncPubTest')
if not published_workspaces:
sharing_id = local_workspace.export(publish=True).wait().id
else:
sharing_id = published_workspaces[0].id
published_workspace = client.get_published_workspace(sharing_id)
owner_name = published_workspace.definition.owner_username
name = published_workspace.name
print(owner_name, name) …
```
=> feat: Add logic in python client for published workspace update

docs/source/modelon.impact.client.rst, docs/source/working_with_workspaces.rst, modelon/impact/client/client.py, modelon/impact/client/entities/workspace.py
This PR adds a documentation section with an example on workspace publishing to cloud storage and importing the workspace back into userspace.
=> chore: added workspace publishing docs

docs/source/working_with_workspaces.rst, modelon/impact/client/__init__.py, modelon/impact/client/entities/workspace.py, modelon/impact/client/published_workspace_client.py, modelon/impact/client/sal/workspace.py, tests/impact/client/entities/test_workspace.py, tests/impact/client/sal/test_workspace_service.py
Code to test
```
import os
os.environ["IMPACT_PYTHON_CLIENT_EXPERIMENTAL"] = "true"
from modelon.impact.client import AccessSettings, Client
client = Client(url="https://jhmi-staging.modelon.com", interactive=True)
pwc = client.get_published_workspaces_client()
workspace = client.get_workspace('abhilash')
workspace.export(publish=True, access=AccessSettings(group_names=[]))
workspace.export(
publish=True, access=AccessSettings(group_names=['impact-tenant-mycompany'])
)
```
=> feat: added possibility to export a workspace without group share

.readthedocs.yml, poetry.lock, pyproject.toml
The RTD builds were failing with the following error
```
Configuration error:
There is a programmable error in your configuration file:
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/modelon-impact-client/envs/update-sphinx/lib/python3.9/site-packages/sphinx/config.py", line 358, in eval_config_file
exec(code, namespace)  # NoQA: S102
File "/home/docs/checkouts/readthedocs.org/user_builds/modelon-impact-client/checkouts/update-sphinx/docs/source/conf.py", line 16, in <module>
import sphinx_rtd_theme
ModuleNotFoundError: No module named 'sphinx_rtd_theme'
```
I looked at the latest build docs available for setups with poetry at https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry and updated our …
=> chore: bump sphinx-rtd-theme version

Makefile, tests/impact/client/fixtures/fixtures.py
This PR fixes a minor issue when a user tries regenerate cassettes for just a single test. In this case, although only the single test cassette is regenerated, the assert for username errors out as the user name doesn't match the one in cassettes
=> Fix fixture

modelon/impact/client/configuration.py, modelon/impact/client/entities/workspace.py, modelon/impact/client/experiment_definition/extension.py, modelon/impact/client/experiment_definition/fmu_based.py, modelon/impact/client/experiment_definition/model_based.py, modelon/impact/client/experiment_definition/modifiers.py, modelon/impact/client/experiment_definition/operators.py, modelon/impact/client/experiment_definition/util.py, modelon/impact/client/sal/workspace.py, mypy.ini, tests/impact/client/test_experiment_definition.py
:warning: :warning: :warning: It is recommended to review commit by commit   :warning: :warning: :warning:
This MR fixes a few bugs found during development (initial fix commits). It adds type consistency checking for the 'choices' operator and adds an experimental mode using V3 of experiment definition.
For testing the experimental V3 functionality:
* Spin up latest impact locally
* Create a workspace test-v3
* Import the library [dataTypes.txt](https://github.com/modelon-community/impact-client-python/files/14744034/dataTypes.txt) (rename file from `.txt` -> `.mo`)
* Run a script like:
```
import os
from modelon.impact.client.experiment_definition.modifiers import Enumeration
from modelon.impact.client.experiment_definition.operators import …
```
=> Add experiment v3 experimental support

docs/source/_static/custom.css, docs/source/conf.py, modelon/impact/client/entities/experiment.py, modelon/impact/client/entities/workspace.py, modelon/impact/client/experiment_definition/extension.py, modelon/impact/client/experiment_definition/fmu_based.py, modelon/impact/client/experiment_definition/model_based.py, tests/impact/client/entities/test_workspace.py
This MR removes the experimental convenience methods as discussed here - https://github.com/modelon-community/impact-client-python/pull/275. Also it exposes some of the internal variables in Experiment definition classes as properties
=> Remove redundant convenience methods

docs/source/spelling_wordlist.txt, modelon/impact/client/entities/case.py, modelon/impact/client/entities/custom_artifact.py, modelon/impact/client/entities/custom_function.py, modelon/impact/client/entities/file_uri.py, modelon/impact/client/entities/interfaces/custom_artifact.py, modelon/impact/client/entities/workspace.py, tests/impact/client/conftest.py, tests/impact/client/entities/test_case.py, tests/impact/client/entities/test_custom_function.py, tests/impact/client/entities/test_workspace.py, tests/impact/client/helpers.py
This PR is a first cut implementation for FileURI data type support 
Code snippet to test
```
import os
os.environ["IMPACT_PYTHON_CLIENT_EXPERIMENTAL"] = "1"
client = Client(url="https://jhmi-staging.modelon.com/", interactive=True)
workspace = client.get_workspace("arne")
uri_cf = workspace.get_custom_function('uri cf')
modelica_resource_ref = workspace.get_modelica_resource_reference(
"Modelica",
resource_path ="Resources/Data/Electrical/Digital/Memory_Matrix.txt"
)
artifact = workspace.get_experiment("modelica_blocks_examples_pid_controller_20240530_130205_319ed9d").get_case('case_1').get_artifact('ABCD')
artifact_resource_ref = artifact.get_uri()
exp_def = …
```
=> FileURI support

modelon/impact/client/entities/case.py, modelon/impact/client/entities/custom_artifact.py, modelon/impact/client/operations/custom_artifact.py, modelon/impact/client/sal/experiment.py
Code to test
Jira - https://modelonproducts.atlassian.net/browse/FLOW-527
```
client = Client(url="http://localhost:8888/impact", interactive=True)
workspace = client.get_workspace("test")
experiment_definition = model.new_experiment_definition(dynamic)
exp = workspace.create_experiment(experiment_definition)
exp = exp.execute().wait()
path= "/home/akn/Downloads/Result 2.csv"
ca_import = case.import_custom_artifact(path, "test")
print(ca_import.status)
ca=ca_import.wait()
print(ca.id)
```
=> Custom artifact import

modelon/impact/client/entities/case.py, modelon/impact/client/entities/result.py, modelon/impact/client/operations/case_result.py, modelon/impact/client/sal/experiment.py
**Jira** - https://modelonproducts.atlassian.net/browse/FLOW-523
**Code to test**
```
import os
os.environ["IMPACT_PYTHON_CLIENT_EXPERIMENTAL"] = "1"
client = Client(url="http://localhost:8888/impact", interactive=True)
workspace = client.get_workspace("test")
experiment_definition = model.new_experiment_definition(dynamic)
case_1 = exp.get_case('case_1')
result = case_1.import_result('/home/akn/Downloads/Result.csv', overwrite=True).wait()
print(result.keys())
```
=> feat: added support for result import to case behind experimental flag

modelon/impact/client/client.py, modelon/impact/client/sal/service.py
This PR fixes such that a user defined context is passed to the unauthenticated HttpClient as well.
=> fix: pass user defined context to unauthenticated HTTPClient

modelon/impact/client/published_workspace_client.py, modelon/impact/client/sal/http.py, modelon/impact/client/sal/project.py, modelon/impact/client/sal/request.py, modelon/impact/client/sal/workspace.py
The requests library supports query strings to be sent for a request in the params arument See https://requests.readthedocs.io/en/latest/user/quickstart/#passing-parameters-in-urls. This is a safer and neater approach than embedding them as raw strings in the url.
=> Query as Params

modelon/__init__.py, modelon/impact/__init__.py
This MR is to unify how other 'modelon-impact-*' packages handles the top level init files. Without this it is for example not possible to source install another 'modelon-impact-*' package if the client package is installed (as only modelon package or installed last).
=> fix: ensure that client can always be imported with other modelon packages in all cases

tests/impact/client/entities/test_model_exe.py
The integration tests were failing due to change in OCT as reported here - https://modelonproducts.atlassian.net/browse/INS-841. (See comments) which added a new internal parameter in the settable parameters.
=> chore: update compile FMU tests to be more deterministic

.secrets/README.md, modelon/impact/client/sal/experiment.py, modelon/impact/client/sal/http.py, modelon/impact/client/sal/request.py, modelon/impact/client/sal/response.py, tests/fixtures/vcr_cassettes/test_case/TestCase.test_case_import_custom_artifact_default_artifact_id.yaml, tests/impact/client/entities/test_case.py
See FLOW-652:
Artifact download end-point can return different content types depending on the file extension. Client should accept any.
=> fix: accept any artifact content type

docs/source/quick_start.rst
This PR improves the quickstart for FMU based experiment with snippet to set simulation and solver options.
=> chore(docs): added quickstart for setting sim opts for fmu based workflow

modelon/impact/client/exceptions.py, modelon/impact/client/operations/base.py, modelon/impact/client/operations/model_executable.py
Wait for status should accept multiple statuses to avoid inf loop when simulation is cancelled (and so status never becomes DONE).
=> fix: wait status now accepts a tuple as well and defaults to (Status.DONE, Status.CANCELLED)

modelon/impact/client/__init__.py, modelon/impact/client/exceptions.py, modelon/impact/client/operations/orphan_cleanup.py, modelon/impact/client/published_workspace_client.py, modelon/impact/client/sal/workspace.py
Jira - https://modelonproducts.atlassian.net/browse/FLOW-614
```
import os  
os.environ["IMPACT_PYTHON_CLIENT_EXPERIMENTAL"] = "true"  
from modelon.impact.client import Client, OrphanPublishedWorkspaceOwner
from urllib3.exceptions import InsecureRequestWarning  
import requests
requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning)
class Context:  
def __init__(self):
self.session = requests.Session()
self.session.verify = False
client = Client('https://impact.local', interactive=True, context=Context())  
pwc = client.get_published_workspaces_client()
user = OrphanPublishedWorkspaceOwner(id="8143248a-49ee-4473-a2ba-c721b9aafb42", username="akn", group_name="impact-tenant-mycompany")
ops = pwc.list_orphans(user)
print(ops, ops.status)
ops.wait()
ops = …
```
=> feat: add api support for cleaning orphaned published ws

modelon/impact/client/sal/request.py
In order for the python-client to uniquely identify itself against the server, we need to add a specific header in order to separate it from other consumers.
=> feat: add user agent that is specific for the client
