modelon-community/impact-client-python

README.md
docs/source/install.rst
pyproject.toml

Clean up on how the project appears on pypi

fix: Updated Readme and pyproject.toml

---

docs/source/setup.rst
modelon/impact/client/client.py
tests/impact/client/test_client.py

fix: Avoid users to hard-code api keys

---

modelon/impact/client/client.py
modelon/impact/client/entities.py
modelon/impact/client/operations.py
modelon/impact/client/options.py
modelon/impact/client/sal/service.py
tests/impact/client/fixtures.py
tests/impact/client/sal/test_services.py
tests/impact/client/test_client.py

feat: Using the case trajectory api to fetch case trajectories

---

docs/source/quick_start.rst
docs/source/tutorial.rst

Docs for the extension feature
@jacobtaxen

chore: Added docs for extension feature

---

modelon/impact/client/client.py

This PR fixes the upload workspace API.

fix: Corrected the upload_workspace api

---

docs/source/conf.py
docs/source/quick_start.rst
docs/source/tutorial.rst
modelon/impact/client/entities.py
modelon/impact/client/experiment_definition.py

Added docs for new model based workflow

fix: Added docs

---

modelon/impact/client/entities.py
modelon/impact/client/experiment_definition.py

Made the modifiers private as this maybe a bit misleading for the user to understand what it means. Also since it can only contain a value if the change is made in the client, it makes it of little use for it to be public

fix: Made fmu.modifier method private

---

modelon/impact/client/client.py
modelon/impact/client/entities.py
modelon/impact/client/operations.py
modelon/impact/client/options.py
modelon/impact/client/sal/service.py
tests/impact/client/fixtures.py
tests/impact/client/sal/test_services.py
tests/impact/client/test_entities.py

```
workspace = client.create_workspace('t6')
model = workspace.upload_fmu(
r"C:\Users\AbhilashKumar\Downloads\Modelica_Blocks_Math_Gain.fmu",
"Workspace",
overwrite=True,
include_patterns=[],
)
```

feat: Added support for FMU import

---

Dockerfile

Also add missing npm dependency.

Install Dockerfile dependencies non-interactive

---

modelon/impact/client/client.py
modelon/impact/client/entities.py
tests/impact/client/fixtures.py
tests/impact/client/test_client.py
tests/impact/client/test_entities.py
tests/impact/client/test_experiment_definition.py
tests/impact/client/test_operations.py

These are just some minor tweaks on work done during the summer.

Minor review fixes

---

modelon/impact/client/sal/service.py

This PR modifies label and description to use defaults values if not explicitly provided.

fix: Modified label and description to defaults

---

modelon/impact/client/sal/service.py
tests/impact/client/fixtures.py
tests/impact/client/sal/test_services.py

Apparently these are no longer desired, @efredriksson-modelon please sanity check the patch.

Remove some unused methods

---

modelon/impact/client/jupyterhub/authorize.py
modelon/impact/client/jupyterhub/sal.py

This resolves the import issue of the client using Python 3.6.

fix: imports that works for Python 3.6

---

docs/source/setup.rst

This PR(https://modelonproducts.atlassian.net/browse/WAMS-9533) adds docs for JupyterHub auth

Api key docs

---

modelon/impact/client/entities/case.py
modelon/impact/client/entities/experiment.py
modelon/impact/client/entities/model.py
modelon/impact/client/entities/workspace.py
modelon/impact/client/experiment_definition/asserts.py
modelon/impact/client/experiment_definition/base.py
modelon/impact/client/experiment_definition/extension.py
modelon/impact/client/operations/base.py
modelon/impact/client/operations/experiment.py
modelon/impact/client/operations/external_result.py
modelon/impact/client/operations/model_executable.py

chore: corrected paths to modules in docstrings

---

modelon/impact/client/entities/__init__.py
modelon/impact/client/entities/case.py
modelon/impact/client/entities/experiment.py
modelon/impact/client/entities/model_executable.py
modelon/impact/client/entities/status.py
modelon/impact/client/operations/__init__.py
setup.cfg

This is a fix for a breaking change that was missed due to a rushed release where the integration tests where not updated beforehand.

fix: compability for accessing status enums for users

---

modelon/impact/client/__init__.py
modelon/impact/client/client.py
modelon/impact/client/entities/project.py
modelon/impact/client/entities/workspace.py
modelon/impact/client/sal/project.py
modelon/impact/client/sal/service.py
modelon/impact/client/sal/workspace.py
tests/impact/client/entities/test_case.py
tests/impact/client/entities/test_experiment.py
tests/impact/client/entities/test_model.py
tests/impact/client/entities/test_model_exe.py
tests/impact/client/entities/test_project.py
tests/impact/client/entities/test_workspace.py
tests/impact/client/fixtures.py
tests/impact/client/helpers.py
tests/impact/client/jupyterhub/test_sal.py
tests/impact/client/operations/test_case.py
tests/impact/client/operations/test_experiment.py
tests/impact/client/operations/test_external_result.py
tests/impact/client/operations/test_model_exe.py
tests/impact/client/sal/test_custom_function_service.py
tests/impact/client/sal/test_experiment_service.py
tests/impact/client/sal/test_model_exe_service.py
tests/impact/client/sal/test_project_service.py
tests/impact/client/sal/test_services.py
tests/impact/client/sal/test_workspace_service.py
tests/impact/client/test_client.py
tests/impact/client/test_experiment_definition.py

**Jira** - https://modelonproducts.atlassian.net/browse/WAMS-10760

fix: added support for new endpoints

---

modelon/impact/client/__init__.py
modelon/impact/client/client.py
modelon/impact/client/entities/project.py
modelon/impact/client/entities/workspace.py
modelon/impact/client/exceptions.py
modelon/impact/client/operations/workspace.py
modelon/impact/client/sal/project.py
modelon/impact/client/sal/workspace.py
tests/impact/client/entities/test_workspace.py
tests/impact/client/fixtures.py
tests/impact/client/helpers.py
tests/impact/client/sal/test_workspace_service.py
tests/impact/client/test_client.py

**Code to test**
```
from modelon.impact.client.entities.workspace import WorkspaceDefinition
workspace = client.get_workspace("test")
definition = workspace.get_shared_definition()
exported_definition_file_path = definition.to_file()
print(f"Successfully exported workspace: {workspace}")
imported_workspace_definition = WorkspaceDefinition.from_file(exported_definition_file_path)
imported_workspace = client.import_from_shared_definition(definition, interactive=True)
print(f"Successfully Imported workspace: {imported_workspace}")
```

Workspace sharing

---

modelon/impact/client/entities/case.py
tests/impact/client/entities/test_case.py
tests/impact/client/fixtures.py

OTRS ticket - https://otrs.modelon.com/index.pl?Action=AgentTicketZoom;TicketID=40844

fix: adding datetimestamps to run_info

---

Dockerfile
modelon/impact/client/client.py
modelon/impact/client/entities/content.py
modelon/impact/client/entities/project.py
modelon/impact/client/exceptions.py
modelon/impact/client/operations/content_import.py
modelon/impact/client/sal/project.py
tests/impact/client/entities/test_project.py
tests/impact/client/fixtures.py
tests/impact/client/helpers.py
tests/impact/client/sal/test_project_service.py
tests/impact/client/sal/test_services.py
tests/impact/client/test_client.py

A few fixes so the client uses the API correctly.

New api fixes

---

modelon/impact/client/entities/workspace.py
tests/conftest.py
tests/impact/client/entities/test_case.py
tests/impact/client/entities/test_custom_function.py
tests/impact/client/entities/test_experiment.py
tests/impact/client/entities/test_model.py
tests/impact/client/entities/test_model_exe.py
tests/impact/client/entities/test_project.py
tests/impact/client/entities/test_workspace.py
tests/impact/client/fixtures/fixtures.py
tests/impact/client/fixtures/jupyterhub.py
tests/impact/client/helpers.py
tests/impact/client/jupyterhub/test_sal.py
tests/impact/client/operations/test_case.py
tests/impact/client/operations/test_experiment.py
tests/impact/client/operations/test_external_result.py
tests/impact/client/operations/test_model_exe.py
tests/impact/client/sal/test_custom_function_service.py
tests/impact/client/sal/test_experiment_service.py
tests/impact/client/sal/test_http_client.py
tests/impact/client/sal/test_model_exe_service.py
tests/impact/client/sal/test_project_service.py
tests/impact/client/sal/test_services.py
tests/impact/client/sal/test_workspace_service.py
tests/impact/client/test_client.py
tests/impact/client/test_experiment_definition.py
tests/impact/client/test_options.py

This PR helps remove the requirement for ugly importing of fixtures in every test. :)

fix: refactored fixtures

---

modelon/impact/client/client.py
modelon/impact/client/entities/case.py
modelon/impact/client/entities/content.py
modelon/impact/client/entities/experiment.py
modelon/impact/client/entities/model.py
modelon/impact/client/entities/project.py
modelon/impact/client/exceptions.py
modelon/impact/client/operations/case.py
modelon/impact/client/operations/experiment.py
modelon/impact/client/operations/model_executable.py
modelon/impact/client/operations/workspace/conversion.py
modelon/impact/client/operations/workspace/exports.py
modelon/impact/client/options.py
modelon/impact/client/sal/workspace.py
tests/impact/client/fixtures/fixtures.py
tests/impact/client/helpers.py
tests/impact/client/sal/test_workspace_service.py
tests/impact/client/test_client.py

You can test it by running:
* poetry install
* poetry shell
* And then execute the Python code:
```
c = Client('<server URL>')
workspace_id = '<workspace ID>'
workspace = c.convert_workspace(workspace_id).wait()
print(workspace.definition.name)
```
on a workspace that should be converted.

Workspace conversion

---

modelon/impact/client/exceptions.py
modelon/impact/client/operations/base.py
modelon/impact/client/operations/external_result.py
tests/impact/client/fixtures/fixtures.py
tests/impact/client/operations/test_external_result.py

This PR fixes so that we catch if the external result upload operation status is 'error'. I also fixed lint and formatting errors for the fixture.py file.

External result fix

---

modelon/impact/client/client.py
modelon/impact/client/entities/case.py
modelon/impact/client/exceptions.py
modelon/impact/client/sal/experiment.py
tests/impact/client/entities/test_case.py
tests/impact/client/entities/test_experiment.py
tests/impact/client/fixtures/fixtures.py
tests/impact/client/helpers.py
tests/impact/client/operations/test_case.py
tests/impact/client/sal/test_experiment_service.py
tests/impact/client/test_client.py
tests/impact/client/test_experiment_definition.py

Jira - https://modelonproducts.atlassian.net/browse/WAMS-11860

feat: add support to fetch artifact ids

---

modelon/impact/client/client.py
modelon/impact/client/entities/case.py
modelon/impact/client/entities/content.py
modelon/impact/client/entities/experiment.py
modelon/impact/client/entities/external_result.py
modelon/impact/client/entities/model.py
modelon/impact/client/entities/model_executable.py
modelon/impact/client/entities/project.py
modelon/impact/client/entities/workspace.py
modelon/impact/client/operations/base.py
modelon/impact/client/operations/case.py
modelon/impact/client/operations/content_import.py
modelon/impact/client/operations/experiment.py
modelon/impact/client/operations/external_result_import.py
modelon/impact/client/operations/model_executable.py
modelon/impact/client/operations/project_import.py
modelon/impact/client/operations/workspace/conversion.py
modelon/impact/client/operations/workspace/exports.py
modelon/impact/client/operations/workspace/imports.py
tests/impact/client/helpers.py
tests/impact/client/operations/imports/test_external_result.py

This PR tries to partly resolve the circular import issues we have in the code base.

fix: partial resolution of circular imports

---

docs/source/conf.py
modelon/impact/client/client.py
modelon/impact/client/entities/case.py
modelon/impact/client/entities/content.py
modelon/impact/client/entities/custom_function.py
modelon/impact/client/entities/experiment.py
modelon/impact/client/entities/model.py
modelon/impact/client/entities/model_executable.py
modelon/impact/client/entities/project.py
modelon/impact/client/entities/workspace.py
modelon/impact/client/experiment_definition/asserts.py
modelon/impact/client/experiment_definition/base.py
modelon/impact/client/experiment_definition/extension.py
modelon/impact/client/experiment_definition/operators.py
modelon/impact/client/operations/base.py
modelon/impact/client/operations/case.py
modelon/impact/client/operations/content_import.py
modelon/impact/client/operations/experiment.py
modelon/impact/client/operations/external_result_import.py
modelon/impact/client/operations/model_executable.py
modelon/impact/client/operations/project_import.py
modelon/impact/client/operations/workspace/conversion.py
modelon/impact/client/operations/workspace/exports.py
modelon/impact/client/operations/workspace/imports.py
modelon/impact/client/options.py
poetry.lock
pyproject.toml
tests/impact/client/test_client.py

This PR fixes the methods and docs corrections for fetching workspace by name. Also added an extension to use sphinx to auto generate type hints for parameters. Made code complaint with google docstrings.

Documentation improvements

---

modelon/impact/client/client.py
modelon/impact/client/entities/project.py
modelon/impact/client/entities/workspace.py
modelon/impact/client/operations/project_import.py
modelon/impact/client/operations/workspace/conversion.py
modelon/impact/client/operations/workspace/imports.py
modelon/impact/client/sal/project.py
modelon/impact/client/sal/workspace.py
tests/impact/client/entities/test_project.py
tests/impact/client/entities/test_workspace.py
tests/impact/client/fixtures/fixtures.py
tests/impact/client/sal/test_project_service.py
tests/impact/client/sal/test_workspace_service.py

This PR contains some fixes for the minor missing API's missed out from the MI REST API

Api coverage

---

docs/source/modelon.impact.client.operations.rst
docs/source/multi_execution_experiments.rst
docs/source/reexecuting_updating_experiments.rst

Jira - https://modelonproducts.atlassian.net/browse/WAMS-12042

fix: documentation improvements

---

modelon/impact/client/options.py
tests/impact/client/test_options.py

Filter should always be sent as a list. We were allowing str inputs which will not work.

Filter should always be sent as a list

---

modelon/impact/client/entities/model_executable.py
modelon/impact/client/sal/http.py
modelon/impact/client/sal/model_executable.py
modelon/impact/client/sal/request.py
modelon/impact/client/sal/response.py
tests/impact/client/entities/test_model_exe.py
tests/impact/client/fixtures/fixtures.py
tests/impact/client/helpers.py
tests/impact/client/sal/test_model_exe_service.py

https://modelonproducts.atlassian.net/browse/FLOW-56

Model description XML

---

modelon/impact/client/client.py
modelon/impact/client/experiment_definition/expansion.py
modelon/impact/client/sal/service.py
poetry.lock
pyproject.toml
tests/impact/client/fixtures/fixtures.py
tests/impact/client/sal/test_experiment_service.py
tests/impact/client/test_client.py

Jira - https://modelonproducts.atlassian.net/browse/FLOW-40
Code to test
```
from modelon.impact.client import Client, Range
client = Client(url="http://127.0.0.1:8888/impact")
workspace = client.get_workspace('test')
model = workspace.get_model("Unnamed.PID_Controller")
model.compile(compiler_options=dynamic.get_compiler_options())
compilations=list(client.get_executions())
print(compilations)
experiment_definition = model.new_experiment_definition(dynamic)
workspace.execute(experiment_definition.with_modifiers({'PI.yMax':Range(11,15,5)}))
workspace.execute(experiment_definition.with_modifiers({'PI.yMax':Range(15,20,5)}))
simulations=list(client.get_executions())
print(simulations)
```

Get executions

---

modelon/impact/client/entities/case.py

This should fix the bad rendering seen in https://modelon-impact-client.readthedocs.io/en/dev/modelon.impact.client.entities.html#modelon.impact.client.entities.case.CaseAnalysis

fix: docstring fixes to improve rendering

---

docs/source/images/sobol_space_coverage.svg
docs/source/index.rst
docs/source/multi_execution_experiments.rst
docs/source/setup_run_experiment.rst
docs/source/sobol_space_coverage.rst
docs/source/spelling_wordlist.txt
modelon/impact/client/experiment_definition/model_based.py
modelon/impact/client/experiment_definition/operators.py

Jira - https://modelonproducts.atlassian.net/browse/FLOW-69

fix: added docs for expansion alorithms

---

modelon/impact/client/entities/case.py
modelon/impact/client/entities/experiment.py
modelon/impact/client/entities/model_executable.py
modelon/impact/client/entities/status.py
modelon/impact/client/operations/base.py

This PR adds docstrings for Status

fix: added docstrings for status

---

modelon/impact/client/entities/workspace.py
modelon/impact/client/sal/workspace.py
tests/impact/client/sal/test_workspace_service.py

Jira - https://modelonproducts.atlassian.net/browse/FLOW-272

feat: add support for exporting publishing app mode workspaces

---

Dockerfile
modelon/impact/client/__init__.py
modelon/impact/client/client.py
modelon/impact/client/entities/model.py
modelon/impact/client/entities/project.py
modelon/impact/client/entities/workspace.py
modelon/impact/client/operations/project_import.py
modelon/impact/client/sal/project.py
tests/impact/client/fixtures/fixtures.py
tests/impact/client/helpers.py
tests/impact/client/sal/test_project_service.py
tests/impact/client/sal/test_workspace_service.py

Jira - https://modelonproducts.atlassian.net/browse/FLOW-337
**Code to test**
```
import requests
from modelon.impact.client import ProjectType, StorageLocation
client = Client()
for project in client.get_projects(storage_location=StorageLocation.SYSTEM, project_type=ProjectType.SYSTEM):
print(project.name)
```

Project type expose

---

modelon/impact/client/client.py
modelon/impact/client/entities/workspace.py
modelon/impact/client/published_workspace_client.py
tests/impact/client/entities/test_workspace.py

Jira - https://modelonproducts.atlassian.net/browse/FLOW-324

fix: add experimental flag for experimental apis

---

modelon/impact/client/entities/workspace.py
modelon/impact/client/sal/workspace.py
tests/impact/client/entities/test_workspace.py

Jira https://modelonproducts.atlassian.net/browse/FLOW-207

feat: added support to grant community access to published workspacce

---

modelon/impact/client/entities/workspace.py
modelon/impact/client/published_workspace_client.py
modelon/impact/client/sal/workspace.py
tests/impact/client/entities/test_workspace.py
tests/impact/client/helpers.py
tests/impact/client/sal/test_workspace_service.py
tests/impact/client/test_published_ws_client.py

This PR adds support for granting and revoking group access to a published workspace

Group grant access

---

modelon/impact/client/client.py
tests/impact/client/fixtures/fixtures.py
tests/impact/client/helpers.py
tests/impact/client/test_client.py

This PR adds support for fetching user data using a method on the client class.

feat: added client method to fetch user data

---

modelon/impact/client/entities/experiment.py

chore: formatting docs for Experiment.get_last_point

---

modelon/impact/client/entities/experiment.py
modelon/impact/client/entities/workspace.py
modelon/impact/client/experiment_definition/extension.py
tests/conftest.py
tests/fixtures/vcr_cassettes/test_workspace/TestWorkspace.test_create_class_based_experiment_definition_from_experiment_result.yaml
tests/fixtures/vcr_cassettes/test_workspace/TestWorkspace.test_create_fmu_based_experiment_definition_from_experiment_result.yaml
tests/impact/client/entities/test_workspace.py

This PR contains a first cut implementation of a utility method to create experiment definition based on existing experiment result.
Future: Add support to do this for case result as well.

feat: added support for fetching experiment definition given a experiment result

---

modelon/impact/client/entities/case.py
modelon/impact/client/entities/experiment.py
modelon/impact/client/entities/model_executable.py
modelon/impact/client/entities/workspace.py
tests/fixtures/vcr_cassettes/test_workspace/TestWorkspace.test_create_class_based_experiment_definition_from_case_result.yaml
tests/fixtures/vcr_cassettes/test_workspace/TestWorkspace.test_create_class_based_experiment_definition_from_experiment_result.yaml
tests/fixtures/vcr_cassettes/test_workspace/TestWorkspace.test_create_fmu_based_experiment_definition_from_experiment_result.yaml
tests/impact/client/entities/test_workspace.py

**Jira** - https://modelonproducts.atlassian.net/browse/FLOW-458

Support for fetching experiment definitions from case result

---

modelon/impact/client/sal/request.py
tests/conftest.py
tests/fixtures/vcr_cassettes/test_client/TestClient.test_get_executions.yaml
tests/fixtures/vcr_cassettes/test_client/TestClient.test_get_executions_for_workspace.yaml
tests/fixtures/vcr_cassettes/test_project/TestProject.test_get_project_size.yaml
tests/impact/client/entities/test_project.py
tests/impact/client/fixtures/fixtures.py
tests/impact/client/test_client.py

This PR contains some fixes mainly aimed at being able to run/reuse the test suite for integration tests as well

Base fixture

---

modelon/impact/client/entities/experiment.py
tests/impact/client/entities/test_experiment.py

This PR adds a convenience label property to the Experiment entity

feat: add convinience label property to the Experiment entity

---

modelon/impact/client/client.py
modelon/impact/client/entities/case.py
modelon/impact/client/entities/custom_function.py
modelon/impact/client/entities/experiment.py
modelon/impact/client/entities/interfaces/case.py
modelon/impact/client/entities/interfaces/experiment.py
modelon/impact/client/experiment_definition/fmu_based.py
modelon/impact/client/experiment_definition/model_based.py
tests/fixtures/vcr_cassettes/test_client/TestClient.test_create_entity_from_reference.yaml
tests/fixtures/vcr_cassettes/test_client/TestClient.test_get_case_by_reference.yaml
tests/fixtures/vcr_cassettes/test_client/TestClient.test_get_experiment_by_reference.yaml
tests/impact/client/conftest.py
tests/impact/client/entities/test_custom_function.py
tests/impact/client/helpers.py
tests/impact/client/test_client.py

Jira - https://modelonproducts.atlassian.net/browse/FLOW-483
This PR adds support for CaseResult and ExperimentResult datatypes in python client

feat: added support for new custom function parameter data types

---

docs/source/authentication_with_modelon_impact.rst

chore: minor update of docs on authentication

---

.readthedocs.yml
docs/source/conf.py

Added code that sets version number in docs when releasing.

chore: corrected version and copyright year in docs

---

modelon/impact/client/entities/custom_function.py
tests/impact/client/conftest.py
tests/impact/client/entities/test_custom_function.py

This PR adds support for VariableNames data type in Custom Function parameters

feat: added support for VariableNames data type for custom function

---

modelon/impact/client/entities/experiment.py
tests/fixtures/vcr_cassettes/test_experiment/TestExperiment.test_cancelled_execution.yaml
tests/fixtures/vcr_cassettes/test_experiment/TestExperiment.test_running_execution.yaml
tests/impact/client/entities/test_experiment.py

Jira - https://modelonproducts.atlassian.net/browse/FLOW-544

fix: remove assertion for simulation completion from experiment entity api's calls

---

modelon/impact/client/entities/workspace.py
tests/impact/client/entities/test_workspace.py

[Jira - https://modelonproducts.atlassian.net/browse/FLOW-609](https://modelonproducts.atlassian.net/browse/FLOW-609)

fix: updated the AccessSettings object with updated protocol for workspace publish

---

modelon/impact/client/client.py
modelon/impact/client/entities/custom_artifact.py
modelon/impact/client/entities/workspace.py

This PR remove experimental flag for api's related to FileURI ,CaseResult and ExperimentResult Custom function datatypes

fix: remove experimental flag for api's related to FileURI ,CaseResult and ExperimentResult Custom function datatypes

---

modelon/impact/client/experiment_definition/operators.py
tests/fixtures/vcr_cassettes/test_workspace/TestWorkspace.test_get_experiment_definition_for_exp_with_choices_operator.yaml
tests/impact/client/entities/test_workspace.py

fix: passing values as positional argument in Choices operator's from_dict method instead of keyword argument

---

.devcontainer/devcontainer.json
.gitignore
Makefile
tests/impact/client/conftest.py

To update vcr cassettes within devcontainer, set the export UPDATE_CASSETTE=1 in Makefile and rebuild the container.

chore: run vcr tests in devcontainer

---

modelon/impact/client/entities/experiment.py
modelon/impact/client/sal/workspace.py
tests/fixtures/vcr_cassettes/test_experiment/TestExperiment.test_experiment_get_total_size.yaml
tests/impact/client/entities/test_experiment.py

This PR fixes - https://modelonproducts.atlassian.net/browse/WAMS-14179

feat: add method for fetching experiment size in Experiment entity
